#!/bin/bash

# Install Ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git vim software-properties-common ansible

# Pull Ansible configuration
ansible-pull -U https://github.com/ppetroskevicius/ansible.git --ask-become-pass --vault-password-file ~/vault_pass.txt
