---
- name: "Kick-start new environment setup"
  hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    public_key: "https://github.com/ppetroskevicius.keys"

  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git.yml
      # - import_tasks: tasks/dotfiles.yml
      # - import_tasks: tasks/private.yml
