---
- name: "Kick-start new environment setup"
  hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"

  tasks:
    - include: tasks/ssh.yml
    - include: tasks/private.yml
