---
- name: Installing stow
  become: true
  apt: 
    name:
      - stow
      - make

- name: Cloning dotfiles
  ansible.builtin.git:
    repo: "git@github.com:ppetroskevicius/dotfiles.git" 
    dest: "~/.dotfiles"
    key_file: "~/.ssh/id_ed25519"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main

- name: Remove old dotfiles
  shell: rm ~/.gitconfig ~/.bashrc

- name: Stow dotfiles
  shell: cd ~/.dotfiles && ./make
