---
- name: Installing stow
  become: true
  apt: 
    name:
      - stow

- name: Cloning dotfiles
  git:
    repo: "git@github.com:ppetroskevicius/dotfiles.git" 
    dest: "~/dotfiles"
    key_file: "~/.ssh/id_ed25519"
    update: yes
    accept_hostkey: yes

- name: Remove old dotfiles
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - ~/.gitconfig
    - ~/.bashrc

- name: Stow dotfiles (build the default target)
  make:
    chdir: ~/dotfiles
