---
- name: Installing stow
  become: true
  apt: 
    name:
      - stow

- name: Cloning dotfiles
  ansible.builtin.git:
    repo: "git@github.com:ppetroskevicius/dotfiles.git" 
    dest: "~/.dotfiles"
    key_file: "~/.ssh/id_ed25519"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main

- name: Remove old dotfiles
  ansible.builtin.file:
    path: 
      - ~/.gitconfig
      - ~/.bashrc
    state: absent

- name: Stow dotfiles (build the default target)
  make:
    chdir: ~/.dotfiles
