---
- name: Add a setting to ~/.gitconfig
  git_config:
    name: user.email
    scope: global
    value: "p.petroskevicius@gmail.com"

- name: Add a setting to ~/.gitconfig
  git_config:
    name: user.name
    scope: global
    value: "Petras Petroskevicius"
