---
- name: Run playbook from private repository
  ansible.builtin.command: pwd
  register: "output"

- debug: var=output.stdout_lines

- name: Run remote playbook
  ansible.builtin.command: ansible-pull -U https://github.com/ppetroskevicius/ansible-private.git 
  
