---
- name: Ensure .ssh directory exists
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory

- name: Install ssh private key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600

- name: Install ssh public key
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644

- name: Get github key and update the authorized_keys file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    key: "{{ public_key }}"
    state: present

